// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.0
// source: internal/model/proto/login.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KickPlayerNotifyErrtype int32

const (
	KickPlayerNotify_NORMAL          KickPlayerNotifyErrtype = 0 // 正常
	KickPlayerNotify_INACTIVE        KickPlayerNotifyErrtype = 1 // 长时间未活动
	KickPlayerNotify_LOGINOTHERPLACE KickPlayerNotifyErrtype = 2 // 在其他地方登录
	KickPlayerNotify_INVALID         KickPlayerNotifyErrtype = 3 // 无效
)

// Enum value maps for KickPlayerNotifyErrtype.
var (
	KickPlayerNotifyErrtype_name = map[int32]string{
		0: "NORMAL",
		1: "INACTIVE",
		2: "LOGINOTHERPLACE",
		3: "INVALID",
	}
	KickPlayerNotifyErrtype_value = map[string]int32{
		"NORMAL":          0,
		"INACTIVE":        1,
		"LOGINOTHERPLACE": 2,
		"INVALID":         3,
	}
)

func (x KickPlayerNotifyErrtype) Enum() *KickPlayerNotifyErrtype {
	p := new(KickPlayerNotifyErrtype)
	*p = x
	return p
}

func (x KickPlayerNotifyErrtype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KickPlayerNotifyErrtype) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_model_proto_login_proto_enumTypes[0].Descriptor()
}

func (KickPlayerNotifyErrtype) Type() protoreflect.EnumType {
	return &file_internal_model_proto_login_proto_enumTypes[0]
}

func (x KickPlayerNotifyErrtype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KickPlayerNotifyErrtype.Descriptor instead.
func (KickPlayerNotifyErrtype) EnumDescriptor() ([]byte, []int) {
	return file_internal_model_proto_login_proto_rawDescGZIP(), []int{5, 0}
}

type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 玩家名
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"` // 玩家昵称
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 玩家头像
	Vip           int32                  `protobuf:"varint,4,opt,name=vip,proto3" json:"vip,omitempty"`          // vip等级
	Balance       float64                `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"` // 玩家余额
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"` // 币种
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_internal_model_proto_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_proto_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_internal_model_proto_login_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PlayerInfo) GetVip() int32 {
	if x != nil {
		return x.Vip
	}
	return 0
}

func (x *PlayerInfo) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *PlayerInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// 0x11001
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loginname     string                 `protobuf:"bytes,1,opt,name=loginname,proto3" json:"loginname,omitempty"`               // 登录名
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                       // 认证token
	GameType      string                 `protobuf:"bytes,3,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"` // 游戏类型
	Version       uint32                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`                  // 客户端版本
	ClientIp      string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"` // 客户端IP (Gateway添加)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_internal_model_proto_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_proto_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_internal_model_proto_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReq) GetLoginname() string {
	if x != nil {
		return x.Loginname
	}
	return ""
}

func (x *LoginReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReq) GetGameType() string {
	if x != nil {
		return x.GameType
	}
	return ""
}

func (x *LoginReq) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LoginReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

// 0x11002 - 登录响应
type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loginname     string                 `protobuf:"bytes,1,opt,name=loginname,proto3" json:"loginname,omitempty"` // 登录名
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`          // 0: 成功, 其他: 失败
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`     // 错误信息
	Info          *PlayerInfo            `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`           // 玩家信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_internal_model_proto_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_proto_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_internal_model_proto_login_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResp) GetLoginname() string {
	if x != nil {
		return x.Loginname
	}
	return ""
}

func (x *LoginResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResp) GetInfo() *PlayerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// 0x11000 - 心跳包
type HeartBeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeat) Reset() {
	*x = HeartBeat{}
	mi := &file_internal_model_proto_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeat) ProtoMessage() {}

func (x *HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_proto_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeat.ProtoReflect.Descriptor instead.
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return file_internal_model_proto_login_proto_rawDescGZIP(), []int{3}
}

func (x *HeartBeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 0x10001 gate -> game
type ConnClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnClose) Reset() {
	*x = ConnClose{}
	mi := &file_internal_model_proto_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnClose) ProtoMessage() {}

func (x *ConnClose) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_proto_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnClose.ProtoReflect.Descriptor instead.
func (*ConnClose) Descriptor() ([]byte, []int) {
	return file_internal_model_proto_login_proto_rawDescGZIP(), []int{4}
}

// 0x11006 - 踢出玩家通知
// 一直收不到包更新玩家时间戳的用户180s后会被踢出,或者被顶号的玩家也会被踢出
type KickPlayerNotify struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SessionId     string                  `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`                               // 会话ID
	Reason        KickPlayerNotifyErrtype `protobuf:"varint,2,opt,name=reason,proto3,enum=proto.KickPlayerNotifyErrtype" json:"reason,omitempty"` // 踢出原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerNotify) Reset() {
	*x = KickPlayerNotify{}
	mi := &file_internal_model_proto_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerNotify) ProtoMessage() {}

func (x *KickPlayerNotify) ProtoReflect() protoreflect.Message {
	mi := &file_internal_model_proto_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerNotify.ProtoReflect.Descriptor instead.
func (*KickPlayerNotify) Descriptor() ([]byte, []int) {
	return file_internal_model_proto_login_proto_rawDescGZIP(), []int{5}
}

func (x *KickPlayerNotify) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KickPlayerNotify) GetReason() KickPlayerNotifyErrtype {
	if x != nil {
		return x.Reason
	}
	return KickPlayerNotify_NORMAL
}

var File_internal_model_proto_login_proto protoreflect.FileDescriptor

const file_internal_model_proto_login_proto_rawDesc = "" +
	"\n" +
	" internal/model/proto/login.proto\x12\x05proto\"\xa4\x01\n" +
	"\n" +
	"PlayerInfo\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x10\n" +
	"\x03vip\x18\x04 \x01(\x05R\x03vip\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\"\x92\x01\n" +
	"\bLoginReq\x12\x1c\n" +
	"\tloginname\x18\x01 \x01(\tR\tloginname\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\tgame_type\x18\x03 \x01(\tR\bgameType\x12\x18\n" +
	"\aversion\x18\x04 \x01(\rR\aversion\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\"~\n" +
	"\tLoginResp\x12\x1c\n" +
	"\tloginname\x18\x01 \x01(\tR\tloginname\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12%\n" +
	"\x04info\x18\x04 \x01(\v2\x11.proto.PlayerInfoR\x04info\")\n" +
	"\tHeartBeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\v\n" +
	"\tConnClose\"\xb0\x01\n" +
	"\x10KickPlayerNotify\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\x127\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1f.proto.KickPlayerNotify.errtypeR\x06reason\"E\n" +
	"\aerrtype\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\f\n" +
	"\bINACTIVE\x10\x01\x12\x13\n" +
	"\x0fLOGINOTHERPLACE\x10\x02\x12\v\n" +
	"\aINVALID\x10\x03B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_internal_model_proto_login_proto_rawDescOnce sync.Once
	file_internal_model_proto_login_proto_rawDescData []byte
)

func file_internal_model_proto_login_proto_rawDescGZIP() []byte {
	file_internal_model_proto_login_proto_rawDescOnce.Do(func() {
		file_internal_model_proto_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_model_proto_login_proto_rawDesc), len(file_internal_model_proto_login_proto_rawDesc)))
	})
	return file_internal_model_proto_login_proto_rawDescData
}

var file_internal_model_proto_login_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_model_proto_login_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_model_proto_login_proto_goTypes = []any{
	(KickPlayerNotifyErrtype)(0), // 0: proto.KickPlayerNotify.errtype
	(*PlayerInfo)(nil),           // 1: proto.PlayerInfo
	(*LoginReq)(nil),             // 2: proto.LoginReq
	(*LoginResp)(nil),            // 3: proto.LoginResp
	(*HeartBeat)(nil),            // 4: proto.HeartBeat
	(*ConnClose)(nil),            // 5: proto.ConnClose
	(*KickPlayerNotify)(nil),     // 6: proto.KickPlayerNotify
}
var file_internal_model_proto_login_proto_depIdxs = []int32{
	1, // 0: proto.LoginResp.info:type_name -> proto.PlayerInfo
	0, // 1: proto.KickPlayerNotify.reason:type_name -> proto.KickPlayerNotify.errtype
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_model_proto_login_proto_init() }
func file_internal_model_proto_login_proto_init() {
	if File_internal_model_proto_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_model_proto_login_proto_rawDesc), len(file_internal_model_proto_login_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_model_proto_login_proto_goTypes,
		DependencyIndexes: file_internal_model_proto_login_proto_depIdxs,
		EnumInfos:         file_internal_model_proto_login_proto_enumTypes,
		MessageInfos:      file_internal_model_proto_login_proto_msgTypes,
	}.Build()
	File_internal_model_proto_login_proto = out.File
	file_internal_model_proto_login_proto_goTypes = nil
	file_internal_model_proto_login_proto_depIdxs = nil
}
